insert into users (user_email, user_phone_number, user_public_id, user_nm, frnds, gender, user_bday, user_interest_id, f_group_id, trnsp, at_spot_id, user_place) values ('jpl@gmail.com','901234567','Joaquim Pires Lopes',1,'M',to_date('1995.01.01','YYYY.MM.DD'),2,3,4,5,'Lisboa');  
insert into users (user_email, user_phone_number, user_public_id, user_nm, frnds, gender, user_bday, user_interest_id, f_group_id, trnsp, at_spot_id, user_place) values ('amf@gmail.com','912345678','Ana Maria Fonseca',2,'F',to_date('1997.03.03','YYYY.MM.DD'),3,4,5,1,'Setúbal');  
insert into users (user_email, user_phone_number, user_public_id, user_nm, frnds, gender, user_bday, user_interest_id, f_group_id, trnsp, at_spot_id, user_place) values ('pa@gmail.com','923456789','Paula Antunes',3,'F',to_date('1996.07.06','YYYY.MM.DD'),4,5,1,2,'Lisboa');  
insert into users (user_email, user_phone_number, user_public_id, user_nm, frnds, gender, user_bday, user_interest_id, f_group_id, trnsp, at_spot_id, user_place) values ('jrs@mac.com','934567890','Joana Ramalho Silva',4,'F',to_date('1984.09.23','YYYY.MM.DD'),5,1,2,3,'Costa da Caparica');  
insert into users (user_email, user_phone_number, user_public_id, user_nm, frnds, gender, user_bday, user_interest_id, f_group_id, trnsp, at_spot_id, user_place) values ('rms@gmail.com','945678901','Rui Manuel Silva',5,'M',to_date('1994.08.15','YYYY.MM.DD'),1,2,3,4,'Cascais');  
insert into users (user_email, user_phone_number, user_public_id, user_nm, frnds, gender, user_bday, user_interest_id, f_group_id, trnsp, at_spot_id, user_place) values ('jps@gmail.com','956789012','João Paulo Santos',1,'M',to_date('1991.11.16','YYYY.MM.DD'),2,3,4,5,'Lisboa');  
insert into users (user_email, user_phone_number, user_public_id, user_nm, frnds, gender, user_bday, user_interest_id, f_group_id, trnsp, at_spot_id, user_place) values ('cfl@gmail.com','967890123','Cristina Fernandes Lopes',2,'F',to_date('1996.01.07','YYYY.MM.DD'),3,4,5,6,'Cascais');  
insert into users (user_email, user_phone_number, user_public_id, user_nm, frnds, gender, user_bday, user_interest_id, f_group_id, trnsp, at_spot_id, user_place) values ('mpl@gmail.com','978901234','Miguel Pinto Leite',3,'M',to_date('1994.01.07','YYYY.MM.DD'),4,5,1,2,'Cascais');  
insert into users (user_email, user_phone_number, user_public_id, user_nm, frnds, gender, user_bday, user_interest_id, f_group_id, trnsp, at_spot_id, user_place) values ('fcr@gmail.com','989012345','Francisco Costa Rosa',4,'M',to_date('1998.02.16','YYYY.MM.DD'),5,1,2,3,'Costa da Caparica');  
insert into users (user_email, user_phone_number, user_public_id, user_nm, frnds, gender, user_bday, user_interest_id, f_group_id, trnsp, at_spot_id, user_place) values ('efp@gmail.com','990123456','Elsa Fialho Pinto',5,'F',to_date('1999.10.29','YYYY.MM.DD'),1,2,3,4,'Costa da Caparica');  

insert into infospot(spot_name, contact_info, spot_address, spt_type, spt_info_prc_id, evnt_id, crowd_spot_id) values ('Misc by Tartar-ia', '918515254', 'Rua da Boavista 14, 1200-067 Lisboa',1,2,3,4)
insert into infospot(spot_name, contact_info, spot_address, spt_type, spt_info_prc_id, evnt_id, crowd_spot_id) values ('Bohemio da Ribeira Restaurante & Bar', '912932007', 'Tv. do Carvalho 27, 1200-097 Lisboa',2,3,4,5)
insert into infospot(spot_name, contact_info, spot_address, spt_type, spt_info_prc_id, evnt_id, crowd_spot_id) values ('SUBA Restaurante', '211573055', 'Hotel Verride Palácio de Santa Catarina, R. de Santa Catarina nº 1, 1200-401 Lisboa',3,4,5,1)
insert into infospot(spot_name, contact_info, spot_address, spt_type, spt_info_prc_id, evnt_id, crowd_spot_id) values ('Epur', '213460519', 'Largo da Academia Nacional de Belas Artes 14, 1200-289 Lisboa',4,5,1,2)
insert into infospot(spot_name, contact_info, spot_address, spt_type, spt_info_prc_id, evnt_id, crowd_spot_id) values ('Bono Lisboa', '937141859', 'Calçada Ferragial 9, 1200-182 Lisboa',5,1,2,3)
